<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\BlogPost;
use Faker\Generator as Faker;

$factory->define(BlogPost::class, function (Faker $faker) {
    return [
        'title' => $faker->sentence(10),
        'content' => $faker->paragraphs(5, true)
    ];
});

$factory->state(App\BlogPost::class, 'new-title-test', function(Faker $faker){
    return [
        'title' => 'New title',                     // this will overwrite the data(title and content ) specify above
        'content' => 'Content of the blog post'     // if you remove it, the content will be autogenerated fro the code above
    ];
});
